import * as fs from 'fs';
import * as path from 'path';
import { Parser } from 'htmlparser2';
/**
 * can optimize <dir>
 * Scans for templates and pre-compiles expressions into a manifest file.
 */
export async function optimize(dir) {
    const expressions = new Set();
    const files = fs.readdirSync(dir, { recursive: true });
    files.forEach(file => {
        if (file.endsWith('.can') || file.endsWith('.html')) {
            const content = fs.readFileSync(path.join(dir, file), 'utf-8');
            extractExpressions(content, expressions);
        }
    });
    let output = '/* Generated by Can Framework Optimizer */\n';
    output += 'export const expressions = {\n';
    expressions.forEach(exp => {
        // Transform expressions: replace 'user' with 'scope.user' but NOT 'name' in 'user.name'
        // Using negative lookbehind (?<!\.) to ensure we don't prefix property accessors
        const transformed = exp.replace(/(?<!\.)\b([a-zA-Z_$][a-zA-Z0-9_$]*)\b/g, (match) => {
            const globals = ['Math', 'Date', 'JSON', 'Object', 'Array', 'true', 'false', 'null', 'undefined', 'window', 'document', 'console', 'String', 'Number', 'Boolean'];
            return globals.includes(match) ? match : `scope.${match}`;
        });
        output += `  '${exp.replace(/'/g, "\\'")}': (scope) => { try { return ${transformed}; } catch { return ''; } },\n`;
    });
    output += '};\n';
    fs.writeFileSync(path.join(dir, 'expressions.mjs'), output);
    console.log(`\x1b[32m[Optimizer]\x1b[0m Pre-compiled ${expressions.size} expressions to expressions.mjs`);
}
function extractExpressions(html, set) {
    const parser = new Parser({
        onattribute(name, value) {
            if (name.startsWith('c-') || name.startsWith(':') || name.startsWith('@')) {
                if (name.startsWith('c-for')) {
                    const exp = value.split(' in ')[1];
                    if (exp)
                        set.add(exp.trim());
                }
                else {
                    set.add(value.trim());
                }
            }
        },
        ontext(text) {
            const matches = text.matchAll(/\{\{(.*?)\}\}/g);
            for (const match of matches) {
                set.add(match[1].trim());
            }
        }
    });
    parser.write(html);
    parser.end();
}
//# sourceMappingURL=optimize.mjs.map