// <!-- Teleport to body -->
// <Teleport to="body">
//     <div class="modal">
//         <h1>I am a modal!</h1>
//         <button @click="close">Close</button>
//     </div>
// </Teleport>
// <!-- Teleport to a specific container -->
// <Teleport to="#modals-container">
//     <div>...</div>
// </Teleport>
import { Component } from "./Component.mjs";
import { effect } from "../reactivity/effect.mjs";
import { warn } from "../shared/index.mjs";
export class Teleport extends Component {
    render() {
        // 1. Create a placeholder that stays in the original DOM tree
        const container = document.createElement('div');
        container.style.display = 'none';
        const teleportedNodes = [];
        // 2. Override appendChild to intercept children generated by the compiler
        container.appendChild = (node) => {
            teleportedNodes.push(node);
            // Try to move immediately if target is resolvable
            const target = this.resolveTarget();
            if (target) {
                target.appendChild(node);
            }
            return node;
        };
        // 3. Handle cleanup: Remove teleported nodes when placeholder is removed
        const originalRemove = container.remove.bind(container);
        container.remove = () => {
            teleportedNodes.forEach(n => {
                if (n.parentNode)
                    n.parentNode.removeChild(n);
            });
            originalRemove();
        };
        // 4. Reactivity: Watch for 'to' prop changes and move nodes
        // Use microtask to ensure props are populated after instantiation
        Promise.resolve().then(() => {
            this._scope.run(() => {
                effect(() => {
                    const target = this.resolveTarget();
                    if (target) {
                        teleportedNodes.forEach(node => {
                            target.appendChild(node);
                        });
                    }
                });
            });
        });
        return container;
    }
    resolveTarget() {
        const props = this.props || {};
        const to = props.to;
        // Unwrap signal if passed as one, otherwise use value
        const selector = (to && typeof to === 'object' && 'value' in to) ? to.value : to;
        if (typeof selector === 'string') {
            const el = document.querySelector(selector);
            if (!el) {
                warn(`[Teleport] Target "${selector}" not found. Falling back to body.`);
                return document.body;
            }
            return el;
        }
        return selector || document.body;
    }
}
//# sourceMappingURL=Teleport.mjs.map